export { buyCake } from './cake/cakeActions'
export { buyIceCream } from './iceCream/iceCreamAction'
export { createTitle } from './CreateTitle/CreateTitleActions'
export { createType } from './CreateType/CreateTypeActions'
export { createQuestions } from './createQuestions/createQuestionsActions'